"""added priority column

Revision ID: c72cbb842809
Revises: 792287a77ff3
Create Date: 2026-04-16 08:48:14.158206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72cbb842809'
down_revision: Union[str, Sequence[str], None] = '792287a77ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notes', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Notes', 'priority')
    # ### end Alembic commands ###
